version: '3'
services:
  #PHP Service
  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    working_dir: /var/www
    image: digitalocean.com/php
    container_name: app-blog
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www
      - ./docker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:stable-alpine
    container_name: webserver-blog
    restart: unless-stopped
    tty: true
    ports:
      - "${DOCKER_APP_PORT}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf/:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  #MySQL Service
  mysql:
    image: mysql:5.7.22
    container_name: blog
    restart: unless-stopped
    tty: true
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_USERNAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/mysql/mysql.cnf:/etc/mysql/mysql.cnf
      - ./docker/database:/var/lib/mysql
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
